version: "2"
services:
  db: &DB
    image: postgres:9.4.5
    ports:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hello_prod

  prod:
    build: .
    ports:
      - 8080
    environment: &ENV
      DATABASE_URL: ecto://user:password@db/hello_prod
    depends_on:
      - "db"
    links:
      - db:db
