db: &DB
  image: postgres:9.4.5
  ports:
    - 5432
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password

prod:
  build: .
  ports:
    - 8080
  environment: &ENV
    DATABASE_URL: ecto://user:password@db/hello_prod
  links:
    - db:db
